# Generated by Django 3.2.9 on 2022-03-06 18:30

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=150)),
                ('type_of_business', models.CharField(choices=[('b2b', 'Venta Mayorista'), ('b2c', 'Venta Minorista'), ('c2c', 'Comércio entre Consumidores'), ('c2b', 'Comércio Especializado'), ('b2a', 'Venta a la Administración Pública'), ('c2a', 'Servicios Especializados a la Administración Pública')], default='b2c', max_length=30)),
                ('on_trial', models.BooleanField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ('name',),
            },
        ),
    ]
