# Generated by Django 3.2.9 on 2022-03-07 02:06

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=150)),
                ('type_of_business', models.CharField(choices=[('b2b', 'Venta Mayorista'), ('b2c', 'Venta Minorista'), ('c2c', 'Comércio entre Consumidores'), ('c2b', 'Comércio Especializado'), ('b2a', 'Venta a la Administración Pública'), ('c2a', 'Servicios Especializados a la Administración Pública')], default='b2c', max_length=30)),
                ('country', models.CharField(choices=[('Argentina', 'Argentina'), ('Albania', 'Albania'), ('Alemania', 'Alemania'), ('Andorra', 'Andorra'), ('Anguila', 'Anguila'), ('Arabia Saudita', 'Arabia Saudita'), ('Armenia', 'Armenia'), ('Aruba', 'Aruba'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaiyán', 'Azerbaiyán'), ('Bahamas', 'Bahamas'), ('Barbados', 'Barbados'), ('Belarús', 'Belarús'), ('Belice', 'Belice'), ('Bermudas', 'Bermudas'), ('Bolivia', 'Bolivia'), ('Brasil', 'Brasil'), ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'), ('Bélgica', 'Bélgica'), ('Caimán', 'Caimán'), ('Camerún', 'Camerún'), ('Canadá', 'Canadá'), ('Checa', 'Checa'), ('Chile', 'Chile'), ('China', 'China'), ('Chipre', 'Chipre'), ('Ciudad del Vaticano', 'Ciudad del Vaticano'), ('Colombia', 'Colombia'), ('Corea del Sur', 'Corea del Sur'), ('Costa Rica', 'Costa Rica'), ('Croacia', 'Croacia'), ('Cuba', 'Cuba'), ('Curazao', 'Curazao'), ('Dinamarca', 'Dinamarca'), ('Ecuador', 'Ecuador'), ('El Salvador', 'El Salvador'), ('Emiratos Árabes Unidos', 'Emiratos Árabes Unidos'), ('Eslovaquia', 'Eslovaquia'), ('Eslovenia', 'Eslovenia'), ('España', 'España'), ('Estados  Unidos', 'Estados  Unidos'), ('Estonia', 'Estonia'), ('Feroe', 'Feroe'), ('Filipinas', 'Filipinas'), ('Finlandia', 'Finlandia'), ('Francia', 'Francia'), ('Gabon', 'Gabon'), ('Georgia', 'Georgia'), ('Ghana', 'Ghana'), ('Gibraltar', 'Gibraltar'), ('Grecia', 'Grecia'), ('Groenlandia', 'Groenlandia'), ('Guatemala', 'Guatemala'), ('Guernsey', 'Guernsey'), ('Honduras', 'Honduras'), ('Hong Kong', 'Hong Kong'), ('Hungría', 'Hungría'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Irlanda', 'Irlanda'), ('Isla de Man', 'Isla de Man'), ('Islandia', 'Islandia'), ('Islas Cook', 'Islas Cook'), ('Islas Marshall', 'Islas Marshall'), ('Islas Turcas y Caicos', 'Islas Turcas y Caicos'), ('Islas Vírgenes Británicas', 'Islas Vírgenes Británicas'), ('Israel', 'Israel'), ('Italia', 'Italia'), ('Jamaica', 'Jamaica'), ('Japón', 'Japón'), ('Jersey', 'Jersey'), ('Kazajistán', 'Kazajistán'), ('Kenia', 'Kenia'), ('Kuwait', 'Kuwait'), ('Letonia', 'Letonia'), ('Liechtenstein', 'Liechtenstein'), ('Lituania', 'Lituania'), ('Luxemburgo', 'Luxemburgo'), ('Macao', 'Macao'), ('Macedonia', 'Macedonia'), ('Malasia', 'Malasia'), ('Malta', 'Malta'), ('Marruecos', 'Marruecos'), ('Mauricio', 'Mauricio'), ('Moldavia', 'Moldavia'), ('Montserrat', 'Montserrat'), ('México', 'México'), ('Mónaco', 'Mónaco'), ('Nauru', 'Nauru'), ('Nigeria', 'Nigeria'), ('Niue', 'Niue'), ('Noruega', 'Noruega'), ('Nueva Zelanda', 'Nueva Zelanda'), ('Pakistán', 'Pakistán'), ('Panamá', 'Panamá'), ('Paraguay', 'Paraguay'), ('Países Bajos', 'Países Bajos'), ('Perú', 'Perú'), ('Polonia', 'Polonia'), ('Portugal', 'Portugal'), ('Reino Unido', 'Reino Unido'), ('República Dominicana', 'República Dominicana'), ('Rumania', 'Rumania'), ('Rusia', 'Rusia'), ('Saint Marteen', 'Saint Marteen'), ('Samoa', 'Samoa'), ('San Cristóbal y Nieves', 'San Cristóbal y Nieves'), ('San Marino', 'San Marino'), ('San Vicente y Granadinas', 'San Vicente y Granadinas'), ('Santa Lucia', 'Santa Lucia'), ('Seicheles', 'Seicheles'), ('Senegal', 'Senegal'), ('Serbia', 'Serbia'), ('Singapur', 'Singapur'), ('Sudáfrica', 'Sudáfrica'), ('Suecia', 'Suecia'), ('Suiza', 'Suiza'), ('Turkmenistán', 'Turkmenistán'), ('Turquía', 'Turquía'), ('Túnez', 'Túnez'), ('Ucrania', 'Ucrania'), ('Uganda', 'Uganda'), ('Uruguay', 'Uruguay'), ('Venezuela', 'Venezuela')], default='Argentina', max_length=30)),
                ('on_trial', models.BooleanField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ('name',),
            },
        ),
    ]
