# Generated by Django 3.2.9 on 2022-03-07 02:06

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Day',
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('type_of_catalog', models.CharField(choices=[('cc', 'Carta (Actividad Gastronómica)'), ('cg', 'Catalógo General')], default='cc', max_length=30)),
                ('description', models.TextField()),
                ('available_for_time', models.TimeField(default='00:00:00')),
                ('available_to_time', models.TimeField(default='00:00:00')),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=catalog.models.catalog_image)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=catalog.models.catalog_image)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('days_available', models.ManyToManyField(to='catalog.DayOfWeek')),
            ],
            options={
                'verbose_name': 'catalog',
                'verbose_name_plural': 'catalogs',
                'ordering': ('name',),
            },
        ),
    ]
